INSERT INTO pergunta (id, categoria, pergunta)
VALUES

    -- Perguntas inglês

    (1, 'ingles', 'Selecione a tradução correta de good morning:'),
    (2, 'ingles', 'Na frase "I wrote a song for you" as palavras I e You podem ser traduzidas como:'),
    (3, 'ingles', 'Qual a tradução da palavra "WHEN"?'),
    (4, 'ingles', 'Qual A tradução da pergunta: "How old are you?'),
    (5, 'ingles', 'Соmо ѕãо еѕсrіtаѕ аѕ соrеѕ amarelo, rosa e vermelho еm іnglêѕ?'),
    (6, 'ingles', 'Como se fala boa tarde em inglês?'),
    (7, 'ingles', 'Como se fala boa noite em inglês?'),
    (8, 'ingles', 'Qual objeto é utilizado para escrever no seu caderno'),
    (9, 'ingles', 'A pessoa que trabalha na escola ensinando os alunos é um(a):'),
    (10, 'ingles', 'Como se fala maçã em inglês?'),
    (11, 'ingles', 'Em qual parte da casa ficam as camas? (local onde você dorme)'),
    (12, 'ingles', 'Qual a tradução correta para Dog?'),
    (13, 'ingles', 'Marque a alternativa que apresenta a tradução das cores: green, blue, black'),
    (14, 'ingles', 'My pencil is BLACK. (Meu lápis é ________________)'),
    (15, 'ingles', 'He loves YELLOW fruits. (Ele adora frutas ________)'),
    (16, 'ingles', 'Lucas tem 2 anos e Fábio tem 7. A soma das idades de Lucas e Fábio é (em inglês)'),
    (17, 'ingles', 'Qual é o resultado da soma: SIX + ONE?'),
    (18, 'ingles', 'na frase "I love dogs and cats", quais animais estão presentes?'),
    (19, 'ingles', 'Ao encontrar um conhecido dizemos:'),
    (20, 'ingles', 'Qual a cor do céu?'),

    -- Perguntas Matemática

    (21, 'matematica', 'Qual o resultado da multiplicação: 7 x 6?'),
    (22, 'matematica', 'Qual dos números abaixo corresponde ao resultado da multiplicação: 8 x 8?'),
    (23, 'matematica', 'Se 1 litro de suco de uva custa 7 reais. Quanto gastarei se eu comprar 8 litros de suco?'),
    (24, 'matematica', 'O senhor Augusto pescou meia dúzia de peixes com 8 Kg cada. Quantos quilogramas de peixes ele pescou?'),
    (25, 'matematica', ' Que palavra completa a frase: O dinheiro no Brasil é chamado de _________.'),
    (26, 'matematica', 'O número 30 em algarismos romanos tem quantas letras?'),
    (27, 'matematica', 'Como é o número 50 em algarismos romanos?'),
    (28, 'matematica', 'Que número corresponde ao número romano LXV?'),
    (29, 'matematica', 'Coloque em ordem crescente:523,125,479,267,357,964,12,91,7.'),
    (30, 'matematica', 'Juliana estava na fila do cinema e era a vigésima. Quantas pessoas estavam antes dela na fila?'),
    (31, 'matematica', 'Próximo de um coqueiro tinham 5 cocos. Quantos faltaram para completar 1 dezena?'),
    (32, 'matematica', 'Maria tem 50 medalhas que ganhou nas competições de natação. Qual a forma correta de escrever por extenso o número de medalhas que Maria ganhou?'),
    (33, 'matematica', 'Quais os números ímpares que ficam entre 10 e 20?'),
    (34, 'matematica', 'No número 1502 qual valor posicional do número 1?'),
    (35, 'matematica', 'Mariana ficou na casa da colega durante uma hora. Ela chegou às 5 horas da tarde. Que horas ela foi embora?'),
    (36, 'matematica', 'Uma garrafa suporta 4L de água,uma jarra suporta 4000ml de água.Qual recipiente suporta mais água?'),
    (37, 'matematica', 'Um metro tem quantos centímetros?'),
    (38, 'matematica', 'Uma loja de roupas vendeu em uma hora 20 camisas, na hora seguinte mais 30, na terceira hora mais 40 e na quarta hora mais 50 camisas. Quantas camisas foram vendidas nestas quatro horas?'),
    (39, 'matematica', 'Qual o resultado na divisão: 63 : 9?'),
    (40, 'matematica', 'Um grupo de 6 amigas saiu para comer uma pizza. O total da conta na pizzaria foi 54 Reais. Elas dividiram igualmente o valor entre cada uma. Quanto cada uma pagou?'),

    -- Perguntas português

    (41, 'portugues', 'A palavra "índole" diz respeito à:'),
    (42, 'portugues', 'O que é um monopólio?'),
    (43, 'portugues', 'Perene é o mesmo que:'),
    (44, 'portugues', 'Notívago é aquele que:'),
    (45, 'portugues', 'Se uma pessoa fez algo a esmo, significa que ela:'),
    (46, 'portugues', 'Qual das pálavras abaixo apresenta erro de grafia?'),
    (47, 'portugues', 'O que é cliche?'),
    (48, 'portugues', 'Meu filho está _________ com os brinquedos dele'),
    (49, 'portugues', 'O coletivo de camelos é: '),
    (50, 'portugues', 'Ufanista é aquele que:'),
    (51, 'portugues', 'Pandemônio tem relação com:'),
    (52, 'portugues', 'Segregar é o mesmo que:'),
    (53, 'portugues', 'Xenofobia consiste em uma aversão a: '),
    (54, 'portugues', 'Um sujeito malcriado, desrespeitoso no que diz ou nas atitudes que toma, é chamado de:'),
    (55, 'portugues', '"Subir para cima" e "descer para baixo" são exemplos de:'),
    (56, 'portugues', 'Concatenar é o mesmo que:'),
    (57, 'portugues', 'Gringo é um:'),
    (58, 'portugues', 'Dogma é um ponto fundamental para'),
    (59, 'portugues', 'Pejorativo é algo que pode:'),
    (60, 'portugues', 'Retaliar significa: '),

    -- Perguntas História

    (61, 'historia', 'Quais os nomes dos governadores gerais que comandaram o Brasil Colonial, respectivamente?'),
    (62, 'historia', 'Quem foi o primeiro presidente eleito por voto popular no Brasil?'),
    (63, 'historia', 'Qual o nome do Poeta brasileiro considerado o poeta dos escravos?'),
    (64, 'historia', 'Quem foi o primeiro colonizador brasileiro?'),
    (65, 'historia', 'Qual foi o local da primeira invasão holandesa?'),
    (66, 'historia', 'Qual poder foi exercido pelo Imperador a partir da primeira Constituição?'),
    (67, 'historia', 'Quem foi o primeiro presidente do Brasil?'),
    (68, 'historia', 'Marque qual foi um forte fator contribuinte para a abdicação de Dom Pedro?'),
    (69, 'historia', 'Um fator que motivou a revolta de Vila Rica?'),
    (70, 'historia', 'Quem foi o presidente que assumiu o poder, a partir da Revolução de 1930?'),
    (71, 'historia', 'Quem descobriu o Brasil?'),
    (72, 'historia', 'Quando foi proclamada a independência do Brasil?'),
    (73, 'historia', 'Famosa revolução ocorrida no estado do Rio Grande do Sul:'),
    (74, 'historia', 'Qual foi a primeira capital do Brasil?'),
    (75, 'historia', 'Data na qual foi proclamada a república no Brasil:'),
    (76, 'historia', 'Como eram chamados os religiosos catequizadores dos povos nativos brasileiros nos anos que seguem o descobrimento e colonização do Brasil?'),
    (77, 'historia', 'Qual o nome do primeiro presidente da República Federativa do Brasil?'),
    (78, 'historia', 'Famoso riacho em cujas margens fora proclamada a Independência do Brasil por Dom Pedro I:'),
    (79, 'historia', 'Qual é o nome da legislação brasileira responsável pela abolição da escravidão em 1888?'),
    (80, 'historia', 'Quem é o autor do hino nacional brasileiro');

INSERT INTO resposta (id, id_pergunta, resposta_correta, descricao)

VALUES (1, 1, false, 'obrigado'),
       (2, 1, false, 'oi'),
       (3, 1, true, 'bom dia'),
       (4, 1, false, 'boa noite'),

       (5, 2, false, 'Ele e Eu'),
       (6, 2, false, 'Ela e Você'),
       (7, 2, true, 'Eu e Você'),
       (8, 2, false, 'Nós e Vocês'),

       (9, 3, true, 'quando'),
       (10, 3, false, 'onde'),
       (11, 3, false, 'talvez'),
       (12, 3, false, 'aqui'),

       (13, 4, false, ' Você está com fome?'),
       (14, 4, false, 'Como vai você?'),
       (15, 4, true, 'Quantos anos você tem?'),
       (16, 4, false, 'Qual seu nome?'),

       (17, 5, false, 'yellow, black, pink'),
       (18, 5, false, ' red, ріnk, green.'),
       (19, 5, true, 'yellow, pink, red.'),
       (20, 5, false, ' ріnk, whіtе, brоwn'),

       (21, 6, false, 'Buenas tarde'),
       (22, 6, false, 'good morning'),
       (23, 6, false, 'good night'),
       (24, 6, true, 'good afternoon'),

       (25, 7, false, 'Buenas noches'),
       (26, 7, true, 'Good night'),
       (27, 7, false, 'Boa noite'),
       (28, 7, false, 'Good morning'),

       (29, 8, false, 'eraser'),
       (30, 8, true, 'pencil'),
       (31, 8, false, 'book'),
       (32, 8, false, 'notebook'),

       (33, 9, false, 'watermelon'),
       (34, 9, false, 'grape'),
       (35, 9, false, 'pineapple'),
       (36, 9, true, 'apple'),

       (37, 10, false, 'doctor'),
       (38, 10, false, 'student'),
       (39, 10, false, 'director'),
       (40, 10, true, 'teacher'),

       (41, 11, false, 'kitchen'),
       (42, 11, false, 'garage'),
       (43, 11, false, 'bathroom'),
       (44, 11, true, 'bedroom'),

       (45, 12, false, 'Leão'),
       (46, 12, false, 'Gato'),
       (47, 12, true, 'Cachorro'),
       (48, 12, false, 'Rato'),

       (49, 13, false, 'Leão'),
       (50, 13, false, 'Gato'),
       (51, 13, true, 'Cachorro'),
       (52, 13, false, 'Rato'),

       (53, 14, false, 'marrom'),
       (54, 14, false, 'Gato'),
       (55, 14, true, 'Cachorro'),
       (56, 14, false, 'Rato'),

       (57, 15, false, 'vermelhas'),
       (58, 15, true, 'amarelas'),
       (59, 15, false, 'verdes'),
       (60, 15, false, 'laranjas'),

       (61, 16, false, 'Seven'),
       (62, 16, false, 'Twelve'),
       (63, 16, false, 'Ten'),
       (64, 16, true, 'Nine'),

       (65, 17, false, '6'),
       (66, 17, false, '5'),
       (67, 17, false, '1'),
       (68, 17, true, '7'),

       (69, 18, false, 'Сасhоrrо е саvаlоs'),
       (70, 18, true, 'Сасhоrrо e gаtоѕ.'),
       (71, 18, false, 'Сасhоrrо е tаrtаrugаѕ'),
       (72, 18, false, ' Сасhоrrо e раtоѕ.'),

       (73, 19, false, 'Bye'),
       (74, 19, false, ' Im sorry'),
       (75, 19, false, 'Thank you'),
       (76, 19, true, 'Hello'),

       (77, 20, false, 'Green'),
       (78, 20, false, 'Red'),
       (79, 20, true, 'Blue'),
       (80, 20, false, 'Yellow'),

       (81, 21, false, '35'),
       (82, 21, false, '36'),
       (83, 21, true, '42'),
       (84, 21, false, '48'),

       (85, 22, false, '36'),
       (86, 22, false, '42'),
       (87, 22, false, '81'),
       (88, 22, true, '64'),

       (89, 23, false, 'Gastarei 15 reais'),
       (90, 23, false, 'Gastarei 45 reais'),
       (91, 23, true, 'Gastarei 56 reais'),
       (92, 23, false, 'Gastarei 63 reais'),

       (93, 24, false, '40'),
       (94, 24, false, '36'),
       (95, 24, true, '48'),
       (96, 24, false, '45'),

       (97, 25, false, 'moedas'),
       (98, 25, true, 'real'),
       (99, 25, false, 'notas'),
       (100, 25, false, 'Nenhuma das respostas anteriores.'),

       (101, 26, false, '1'),
       (102, 26, false, '2'),
       (103, 26, true, '3'),
       (104, 26, false, '4'),

       (105, 27, false, 'X'),
       (106, 27, false, 'C'),
       (107, 27, false, 'D'),
       (108, 27, true, 'L'),

       (109, 28, false, '45'),
       (110, 28, false, '50'),
       (111, 28, true, '65'),
       (112, 28, false, '60'),

       (113, 29, false, '964>523>479>357>267>125>91>12>7.'),
       (114, 29, true, '7<12<91<125<267<357<479<523<964.'),
       (115, 29, false, '523<125<479<267<357<964<12<91<7.'),
       (116, 29, false, '7<12<91<125<267<479<357<523<964.'),

       (117, 30, false, '20 pessoas'),
       (118, 30, false, '10 pessoas'),
       (119, 30, true, '19 pessoas'),
       (120, 30, false, '15 pessoas'),

       (121, 31, false, '6 cocos'),
       (122, 31, false, '4 cocos'),
       (123, 31, true, '5 cocos'),
       (124, 31, false, '7 cocos'),

       (125, 32, false, 'simquenta'),
       (126, 32, false, 'cimqueta'),
       (127, 32, true, 'cinquenta'),
       (128, 32, false, 'sinquenta'),

       (129, 33, false, '11, 12, 14, 16, e 19'),
       (130, 33, false, '12, 13, 14, 15, 16, 17 e 18'),
       (131, 33, false, '11, 12, 14, 16 e 18'),
       (132, 33, true, '11, 13, 15, 17 e 19'),

       (133, 34, true, '1000'),
       (134, 34, false, '100'),
       (135, 34, false, '1'),
       (136, 34, false, '10'),

       (137, 35, false, '5 horas'),
       (138, 35, false, '6 horas e 30 minutos'),
       (139, 35, true, '6 horas'),
       (140, 35, false, 'Nenhuma das respostas anteriores.'),

       (141, 36, false, 'A jarra'),
       (142, 36, true, 'Os dois recipientes suportam a mesma quantidade de água'),
       (143, 36, false, 'A garrafa'),
       (144, 36, false, 'Nenhuma das respostas anteriores.'),

       (145, 37, false, '50'),
       (146, 37, false, '60'),
       (147, 37, false, '90'),
       (148, 37, true, '100'),

       (149, 38, true, '140'),
       (150, 38, false, '141'),
       (151, 38, true, '139'),
       (152, 38, false, '142'),

       (153, 39, false, '9'),
       (154, 39, false, '8'),
       (155, 39, false, '10'),
       (156, 39, true, '7'),

       (157, 40, false, 'Cada amiga pagou 8 Reais'),
       (158, 40, false, 'Cada amiga pagou 12 Reais.'),
       (159, 40, true, 'Cada amiga pagou 9 Reais.'),
       (160, 40, false, 'Cada amiga pagou 15 Reais.'),


       (161, 41, false, 'ao índice de um livro'),
       (162, 41, false, 'ao início de um parágrafo'),
       (163, 41, false, 'ao cruzamento de espécies diferentes'),
       (164, 41, false, 'à altura de uma pessoa'),
       (165, 41, true, 'ao caráter de uma pessoa'),

       (166, 42, true, 'venda de produtos ou serviços sem concorrentes, por preços abusivos'),
       (167, 42, false, 'produto do tipo saponáceo, ou seja, que tem as características de sabão'),
       (168, 42, false, 'produto usado para fazer um bolo crescer'),
       (169, 42, false, 'estado de grande confusão; situação difícil; mal-entendido'),
       (170, 42, false, 'dispositivo eletrônico cuja tela apresenta apenas tons de cinza'),

       (171, 43, true, 'eterno, perpétuo'),
       (172, 43, false, 'calmo, tranquilo'),
       (173, 43, false, 'duro, difícil'),
       (174, 43, false, 'fácil, descomplicado'),
       (175, 43, false, 'grandioso, gigante'),

       (176, 44, false, 'faz anotações'),
       (177, 44, false, 'dá notas para os alunos'),
       (178, 44, false, 'monta automóveis'),
       (179, 44, true, 'tem hábitos noturnos'),
       (180, 44, false, 'trabalha com notas musicais'),

       (181, 45, false, 'cozinhou usando torresmo'),
       (182, 45, false, 'fez um trabalho espetacular'),
       (183, 45, false, 'trabalhou em um local escuro'),
       (184, 45, true, 'fez algo sem certeza, sem exatidão'),
       (185, 45, false, 'praticou uma atividade a cavalo'),

       (186, 46, false, 'bruxa'),
       (187, 46, false, 'enxugar'),
       (188, 46, false, 'encher'),
       (189, 46, false, 'xingar'),
       (190, 46, true, 'mecher'),

       (191, 47, false, 'local para pagamentos e recebimentos'),
       (192, 47, false, 'goma de mastigar'),
       (193, 47, false, 'frase frequentemente repetida'),
       (194, 47, true, 'trabalho feito à mão com uma agulha especial'),
       (195, 47, false, 'remuneração que um ator recebe por novela'),

       (196, 48, false, 'intretido'),
       (197, 48, false, 'intertido'),
       (198, 48, true, 'entretido'),
       (199, 48, false, 'entertido'),
       (200, 48, false, 'entetido'),

       (201, 49, false, 'colmeia'),
       (202, 49, false, 'alcateia'),
       (203, 49, false, 'matilha'),
       (204, 49, true, 'cáfila'),
       (205, 49, false, 'miríade'),

       (206, 50, false, 'estuda os extraterrestres'),
       (207, 50, true, 'tem grande orgulho do país em que nasceu'),
       (208, 50, false, 'vive no continente europeu'),
       (209, 50, false, 'cria unicórnios'),
       (210, 50, false, 'coleciona moedas de vários países'),

       (211, 51, true, 'confusão'),
       (212, 51, false, 'diabo'),
       (213, 51, false, 'fabricação de pães'),
       (214, 51, false, 'epidemia'),
       (215, 51, false, 'tecnologia'),

       (216, 52, false, 'juntar'),
       (217, 52, false, 'apostar'),
       (218, 52, false, 'agregar'),
       (219, 52, true, 'separar'),
       (220, 52, false, 'convidar'),

       (221, 53, false, 'ratos'),
       (222, 53, false, 'locais fechados'),
       (223, 53, false, 'altura'),
       (224, 53, false, 'avião'),
       (225, 53, true, 'estrangeiros'),

       (226, 54, true, 'insolente'),
       (227, 54, false, 'sagaz'),
       (228, 54, false, 'erudito'),
       (229, 54, false, 'venerado'),
       (230, 54, false, 'benquisto'),

       (231, 55, true, 'pleonasmo'),
       (232, 55, false, 'eufemismo'),
       (233, 55, false, 'metáfora'),
       (234, 55, false, 'ironia'),
       (235, 55, false, 'demagogia'),

       (236, 56, false, 'chorar'),
       (237, 56, true, 'unir, ligar'),
       (238, 56, false, 'vender algo'),
       (239, 56, false, 'juntar conchas na praia'),
       (240, 56, false, 'ligar uma antena'),

       (241, 57, false, 'tipo de grilo'),
       (242, 57, false, 'sino'),
       (243, 57, true, 'indivíduo estrangeiro'),
       (244, 57, false, 'tipo de pastel'),
       (245, 57, false, 'instrumento musica'),

       (246, 58, false, 'a criação de cachorros'),
       (247, 58, true, 'uma doutrina religiosa'),
       (248, 58, false, 'a preservação da saúde'),
       (249, 58, false, 'preservação do meio ambiente'),
       (250, 58, false, 'plantar cenouras'),

       (251, 59, false, 'alegrar'),
       (252, 59, true, 'ofender'),
       (253, 59, false, 'crescer'),
       (254, 59, false, ' cair'),
       (255, 59, false, 'agradar'),

       (256, 60, false, 'cortar em pedaços'),
       (257, 60, false, 'dividir em duas partes'),
       (258, 60, true, 'revidar'),
       (259, 60, false, 'remendar'),
       (260, 60, false, 'emendar'),


       (261, 61, true, 'Tomé de Souza, Duarte da Costa e Mem de Sá.'),
       (262, 61, false, 'Cabral, Dom João VI e Tomé de Souza.'),
       (263, 61, false, 'Tiradentes, Tomé de Souza e Estácio de Sá.'),
       (264, 61, false, 'Tomé de Souza, Duarte da Costa e Estácio de Sá.'),
       (265, 61, false, 'Dom João IV, Cristóvão Colombo e Cabral.'),

       (266, 62, false, 'Fernando Henrique.'),
       (267, 62, false, 'Floriano Peixoto.'),
       (268, 62, false, 'Deodoro da Fonseca.'),
       (269, 62, false, 'Dom Pedro.'),
       (270, 62, true, 'Prudente de Morais.'),

       (271, 63, false, 'Drummond de Andrade.'),
       (272, 63, false, 'Emmanuel Kant.'),
       (273, 63, true, 'Castro Alves.'),
       (274, 63, false, 'Manuel Bandeira'),
       (275, 63, false, 'Nenhuma das respostas'),

       (276, 64, true, 'Martim Afonso de Souza.'),
       (277, 64, false, 'Pedro de Alcântara.'),
       (278, 64, false, 'Tomé de Souza.'),
       (279, 64, false, 'Duque de Caxias.'),
       (280, 64, false, 'Barrão do Rio Branco.'),

       (281, 65, false, 'Rio de Janeiro.'),
       (282, 65, true, 'Salvador.'),
       (283, 65, false, 'Grão-Pará.'),
       (284, 65, false, 'Acre.'),
       (285, 65, false, 'Minas Gerais.'),

       (286, 66, false, 'Legislativo.'),
       (287, 66, false, 'Judiciário.'),
       (288, 66, true, 'Moderador'),
       (289, 66, false, 'Executivo.'),
       (290, 66, false, 'Nenhuma das respostas.'),

       (291, 67, false, 'Marechal Floriano Peixoto.'),
       (292, 67, false, 'Castro Alves.'),
       (293, 67, false, 'Castelo Branco.'),
       (294, 67, true, 'Deodoro da Fonseca'),
       (295, 67, false, 'Nenhuma das respostas.'),

       (296, 68, false, 'Revoltas nacionais.'),
       (297, 68, false, 'Morte de seu filho.'),
       (298, 68, false, 'Exigência de Portugal.'),
       (299, 68, true, 'A crise financeira de 1829, que fechou o Banco do Brasil.'),
       (300, 68, false, 'Nenhuma das respostas.'),

       (301, 69, false, 'A aplicação da Derrama.'),
       (302, 69, false, 'Não queriam que o ouro fosse levado para Portugal.'),
       (303, 69, false, 'A revolta queria implantar a República.'),
       (304, 69, true, 'A criação das casas de fundição.'),
       (305, 69, false, 'Nenhuma das respostas.'),

       (306, 70, false, 'Floriano Peixoto.'),
       (307, 70, true, 'Getúlio Vargas.'),
       (308, 70, false, 'Fernando Henrique.'),
       (309, 70, false, 'Rodriguez Alves.'),
       (310, 70, false, 'Estácio de Sá.'),

       (311, 71, false, 'Cristovão Colombo'),
       (312, 71, false, 'Dom Pedro I'),
       (313, 71, false, 'Dom João IV'),
       (314, 71, true, 'Pedro Alvares Cabral'),
       (315, 71, false, 'Pedro de Lara'),

       (316, 72, false, '15 de novembro'),
       (317, 72, false, '12 de outubro'),
       (318, 72, false, '25 de dezembro'),
       (319, 72, false, '1º de abril'),
       (320, 72, true, '7 de setembro'),

       (321, 73, false, 'Revolução Russa'),
       (322, 73, true, 'Revolução Farroupilha'),
       (323, 73, false, 'Revolução Industrial'),
       (324, 73, false, 'Revolução Francesa'),
       (325, 73, false, 'Revolução Gaúcha'),

       (326, 74, true, 'Salvador'),
       (327, 74, false, 'Rio de janeiro'),
       (328, 74, false, 'Recife'),
       (329, 74, false, 'Porto Seguro'),
       (330, 74, false, 'São Vicente'),

       (331, 75, false, '7 de setembro'),
       (332, 75, false, '25 de dezembro'),
       (333, 75, true, '15 de novembro'),
       (334, 75, false, '21 de abri'),
       (335, 75, false, '1 de janeiro'),

       (336, 76, false, 'Catequistas'),
       (337, 76, false, 'Monges Católicos'),
       (338, 76, true, 'Jesuítas'),
       (339, 76, false, 'Padres Ortodoxos'),
       (340, 76, false, 'Irmão de Deus'),

       (341, 77, false, 'Dom Pedro II'),
       (342, 77, false, 'Dilma Rousseff'),
       (343, 77, false, 'Marechal Castelo Branco'),
       (344, 77, true, 'Marechal Deodoro da Fonseca'),
       (345, 77, false, 'Rui Barbosa'),

       (346, 78, false, 'Tietê'),
       (347, 78, true, 'Ipiranga'),
       (348, 78, false, 'Plácido'),
       (349, 78, false, 'Pardinho'),
       (350, 78, false, 'Itaporanga'),

       (356, 79, false, 'Lei dos Escravos'),
       (357, 79, false, 'Lei Rósea'),
       (358, 79, true, 'Lei Áurea'),
       (359, 79, false, 'Lei Seca'),
       (360, 79, false, 'Lei da República'),

       (356, 80, true, 'Joaquim Osório Duque Estrada'),
       (357, 80, false, 'Rui Barbosa'),
       (358, 80, false, 'Joaquim Silvério'),
       (359, 80, false, 'Castelo Branco'),
       (360, 80, false, 'João Carlos Nóbrega');
